name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c release -o SecondDimensionWatcher-Alapha
    - name: Pack Publish
      run: tar czvf SecondDimensionWatcher-Alapha.tar.gz SecondDimensionWatcher-Alapha
    - name: Delete Old Prerelease
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        tag_name: alapha-0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish GitHub Release
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        bodyFile: AlaphaReleaseNote.md
        artifacts: SecondDimensionWatcher-Alapha.tar.gz
        tag: alapha-0.1
        token: ${{ secrets.GITHUB_TOKEN }}
    

  